name: Build payload

on: [ push, pull_request ]

jobs:
  payload-build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./build.sh
        shell: bash

    - name: Upload payload
      uses: actions/upload-artifact@v3
      with:
        name: ftps5
        path: ./*.elf
        if-no-files-found: error
