name: Build payload

on: push

jobs:
  payload-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set env vars
      run: |
        echo "llvm_ver=9" >> $GITHUB_ENV
        echo "elfname=ftps5.elf" >> $GITHUB_ENV

    - name: Set up GCC
      uses: illusion0001/gha-setup-gcc@master
      with:
        version: ${{ env.llvm_ver }}
        platform: x64

    - name: Build ${{ env.elfname }}
      run: make

    - name: Upload payload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.elfname }}
        path: ${{ env.elfname }}
        if-no-files-found: error
